// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW8KWui9CONAbOA-yCrfUXMfTKLTIVgEE',
    appId: '1:901600470237:web:c5060f31b451de23e72734',
    messagingSenderId: '901600470237',
    projectId: 'push-notifications-ec273',
    authDomain: 'push-notifications-ec273.firebaseapp.com',
    storageBucket: 'push-notifications-ec273.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCeOhopv-A6duK1UZSQ0befOdvGDFVaSg',
    appId: '1:120006854123:android:38eb68d88a1bb8df4805ae',
    messagingSenderId: '120006854123',
    projectId: 'generasi-sehat',
    storageBucket: 'generasi-sehat.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUFw0kt9B3cei_wGHZqaAXmBs7KmPVr9M',
    appId: '1:120006854123:ios:daba2f6082f994d94805ae',
    messagingSenderId: '120006854123',
    projectId: 'generasi-sehat',
    storageBucket: 'generasi-sehat.firebasestorage.app',
    iosBundleId: 'com.example.taPa2Pa3Project',
  );
}
